default: &default
  adapter: postgresql
  host: localhost
  username: gnilrets

development:
  <<: *default
  database: amylase-dev

test:
  <<: *default
  database: amylase-test

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

