default: &default
  adapter: postgresql
  host: localhost
  username: <%= `whoami` %>

development:
  <<: *default
  database: itk-etl-manager-dev

test:
  <<: *default
  database: itk-etl-manager-test

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
