# Envcrypt - DO NOT SET THE PRODUCTION KEY HERE, KEEP IT AS AN ENVIRONMENT VARIABLE
envcrypt_key: <%= ENV['ENVCRYPT_KEY'] %>

# AWS configuration settings
aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_key:    <%= ENV['AWS_SECRET_KEY'] %>
  region:        us-west-2

# Some parameters only needed during test (set these values in settings.local.yml, the values given here are examples only)
test:
  # Location of an s3 file to test getting data from s3
  s3_file: s3://amylase/test/random.txt
